#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $HUSTLE_REPO == "Hustlebot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2thYWwwNDA4L01lb3dVc2VyYm90L2FyY2hpdmUvbWFpbi56aXA=" | base64 -d
    elif [[ $HUSTLE_REPO == "Hustlebot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2thYWwwNDA4L01lb3dVc2VyYm90L2FyY2hpdmUvbWFpbi56aXA=" | base64 -d
    elif [[ $HUSTLE_REPO =~ $regex ]]
    then
        if [[ $HUSTLE_REPO_BRANCH ]]
        then
            echo "${HUSTLE_REPO}/archive/${HUSTLE_REPO_BRANCH}.zip"
        else
            echo "${HUSTLE_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL2thYWwwNDA4L01lb3dVc2VyYm90L2FyY2hpdmUvbWFpbi56aXA=" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="Hustleuserbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    HUSTLEPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $HUSTLEPATH
    echo "  • Starting Hustlebot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m Hustlebot
}

start_bot
